pkg: config
dest: "./"
fmt: true
compression:
  compress: false
  method: "bestcompression"
  keep: false
clean: false
output: "ab0x.go"
unexporTed: false
spread: true
lcf: true
custom:
- files:
  - "../docs/references/*.yaml"
  base: "../docs/references/"
  prefix: "data"